spring:
  datasource:
    password: 111
    url: jdbc:h2:mem:testdb
    username: finaluser_1
    driver-classname: org.h2.Driver
  h2:
    console:
      path: /h2-console
      enabled: true
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  config:
    activate:
      on-profile: local
  url:
    server: http://localhost:8080
    client: http://localhost:3000

  jwt:
    secret: verySecretUniqueKey
    secretRefresh: wannaRefresh?
    secretPasswordReset: you_forgot_it_again!
    secretPasswordUpdate: ok_try_again!
    expiration: 7200000
    expirationRefresh: 604800000
    expirationPasswordReset: 86400000
    expirationPasswordUpdate: 3600000
    header: Authorization





