spring:
  datasource:
    password: NYNHiv1g-wzTCRqUsLAVdSJwRfXZVC-q
    url: jdbc:postgresql://hattie.db.elephantsql.com/ucivlcsx
    username: ucivlcsx
    driver-classname: org.postgresql.Driver
    schema: classpath:/schema.sql
    continue-on-error: true
    initialize: true
    initialization-mode: always
  output:
    ansi:
      enabled: always
  flyway:
    enabled: true
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: false
  sql:
    init:
      mode: always
  config:
    activate:
      on-profile: remote
  url:
    server: http://localhost:8080
    additional-websockets-port: 8081
    client: http://localhost:3000
  mail:
    host: smtp.gmail.com
    port: 587
    username: fe8fs2finalstep@gmail.com
    password: wwnylhovzmybunoq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 833649741221-eijh9fedi04psm4e9pfvu3atkbarj3bg.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "{baseUrl}/api/v1/auth/login/oauth2/code/google"
            scope:
              - email
              - profile
          facebook:
            clientId: 1414897055753643
            clientSecret: 92063b75a2f7a689f0b90d4b7ecfcecf
            redirectUri: "{baseUrl}/api/v1/auth/login/oauth2/code/facebook"
            scope:
              - email
              - public_profile
              - user_birthday
        provider:
          facebook:
            user-info-uri: "https://graph.facebook.com/me?fields=name,email,picture,first_name,birthday"
  mvc:
    view:
      prefix: /templates/
      suffix: .html
jwt:
  secret: verySecretUniqueKey
  secretRefresh: wannaRefresh?
  secretPasswordReset: you_forgot_it_again!
  secretPasswordUpdate: ok_try_again!
  secretRegister: welcomeOnBoard!
  expiration: 7200000 #2h
  expirationRefresh: 604800000 #7d
  expirationPasswordReset: 86400000 #24h
  expirationPasswordUpdate: 3600000 #1h
  expirationRegister: 86400000 #24h
  header: Authorization
cloudinary:
  cloudName: dojrbfnaz
  apiKey: 516471726946834
  apiSecret: JokricYXIJmtjF29Ptgm2H7FusA
